[workspace]
members = [
  "dex",
  "dex/elrond_dex_farm",
  "dex/elrond_dex_farm/abi",
  "dex/elrond_dex_pair",
  "dex/elrond_dex_pair/abi",
  "dex/elrond_dex_router",
  "dex/elrond_dex_router/abi",

  "sc-locked-asset-factory",
  "sc-locked-asset-factory/abi",

]
