[workspace]
members = [
  "dex",
  "dex/farm",
  "dex/farm/meta",
  "dex/farm-staking",
  "dex/farm-staking/meta",
  "dex/farm_with_lock",
  "dex/farm_with_lock/meta",
  "dex/pair",
  "dex/pair/meta",
  "dex/router",
  "dex/router/meta",

  "locked-asset/",
  "locked-asset/distribution",
  "locked-asset/distribution/meta",
  "locked-asset/proxy-dex",
  "locked-asset/proxy-dex/meta",
  "locked-asset/factory",
  "locked-asset/factory/meta",

  "price-discovery",
  "price-discovery/meta",
  "pair-mock",
  "pair-mock/meta"
]
