[package]
name = "pair-mock-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.pair-mock]
path = ".."

[dependencies.elrond-wasm]
version = "0.27.3"

[dependencies.elrond-wasm-debug]
version = "0.27.3"
