[package]
name = "elrond_dex_pair-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.elrond_dex_pair]
path = ".."

[dependencies.elrond-wasm]
version = "0.14"
path = "../../../elrond-wasm-rs/elrond-wasm"

[dependencies.elrond-wasm-debug]
version = "0.14"
path = "../../../elrond-wasm-rs/elrond-wasm-debug"

