[package]
name = "factory"
publish = false
version = "0.0.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.itertools]
version = "0.10.1"
default-features = false

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.token_merge]
path = "../../common/modules/token_merge"

[dependencies.elrond-wasm]
version = "0.25.0"
features = ["cb_closure_managed_deser"]

[dev-dependencies.elrond-wasm-debug]
version = "0.25.0"

[dependencies]
wee_alloc = "0.4"
arrayvec = { version = "0.7.1", default-features = false }
