[package]
name = "factory"
publish = false
version = "0.0.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.token_supply]
path = "../../common/modules/token_supply"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.token_merge]
path = "../../common/modules/token_merge"

[dependencies.elrond-wasm]
version = "0.22.3"

[dev-dependencies.elrond-wasm-debug]
version = "0.22.3"
