[package]
edition = "2018"
name = "sc_distribution_rs"
publish = false
version = "0.0.0"

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [
  "elrond-wasm-node",
  "asset/wasm-output-mode",
  "global-op/wasm-output-mode",
]

[dependencies.distrib-common]
path = "../distrib-common"

[dependencies.asset]
path = "../modules/asset"

[dependencies.global-op]
path = "../modules/global-op"

[dependencies.sc-locked-asset-factory]
path = "../../sc-locked-asset-factory"

[dependencies.elrond-wasm]
version = "0.17"

[dependencies.elrond-wasm-derive]
version = "0.17"

[dependencies.elrond-wasm-node]
optional = true
version = "0.17"

[dev-dependencies.elrond-wasm-debug]
version = "0.17"
