[package]
name = "multi_token_farm-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.multi_token_farm]
path = ".."

[dependencies.elrond-wasm]
version = "0.20"
features = ["derive"]

[dependencies.elrond-wasm-debug]
version = "0.20"
path = "../../../../elrond-wasm-rs/elrond-wasm-debug"
