[package]
name = "sc_distribution_rs-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.sc_distribution_rs]
path = ".."

[dependencies.elrond-wasm]
version = "0.20"
features = ["derive"]


[dependencies.elrond-wasm-debug]
version = "0.20"

