[package]
name = "governance"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/contract.rs"

[dependencies.elrond-wasm]
version = "0.28"
features = ["cb_closure_managed_deser"]

[dev-dependencies.elrond-wasm-debug]
version = "0.28"
