[package]
name = "elrond_dex_staking-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.elrond_dex_staking]
path = ".."

[dependencies.elrond-wasm]
version = "0.15"

[dependencies.elrond-wasm-debug]
version = "0.15"
