[package]
name = "simple-lock-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]

[dependencies.simple-lock]
path = ".."

[dependencies.elrond-wasm]
version = "0.32.0"

[dependencies.elrond-wasm-debug]
version = "0.32.0"
