[package]
name = "dex-tests"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.elrond-wasm]
version = "0.22.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.22.1"

[dependencies.farm]
path = "farm"

[dependencies.pair]
path = "pair"

[dependencies.router]
path = "router"
