[package]
name = "dex-tests"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.elrond-wasm]
version = "0.25.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.25.0"

[dev-dependencies]
num-bigint = "0.4.2"

[dev-dependencies.config]
path = "../common/modules/config"

[dev-dependencies.rewards]
path = "../common/modules/rewards"

[dev-dependencies.common_structs]
path = "../common/common_structs"

[dependencies.farm]
path = "farm"

[dependencies.pair]
path = "pair"

[dependencies.router]
path = "router"
