[package]
name = "sc-proxy-dex-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.sc-proxy-dex]
path = ".."

[dependencies.elrond-wasm]
version = "0.16"


[dependencies.elrond-wasm-debug]
version = "0.16"

