[package]
name = "locking_module"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]
edition = "2018"

[lib]
path = "src/locking_module.rs"

[dependencies.elrond-wasm]
version = "0.33.0"

[dependencies.simple-lock]
path = "../../../locked-asset/simple-lock"
