[package]
name = "pause-all"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.pausable]
path = "../common/modules/pausable"

[dependencies.elrond-wasm]
version = "0.33.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.33.0"

[dev-dependencies.farm]
path = "../dex/farm"

[dev-dependencies.pair]
path = "../dex/pair"
