name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # See: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
    container: 
      image: elrondnetwork/elrond-sdk-erdpy-rust:latest
      # See: https://github.com/actions/checkout/issues/47
      # User "elrond" has UID = 1001 (specified on the image)
      options: --user elrond:elrond
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Build WASM files
        run: |
          # https://github.com/actions/runner/issues/863
          export HOME=/home/elrond
          erdpy deps check rust
          erdpy deps check wasm-opt
          bash ./build-wasm.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-contracts
          path: |
            ./**/output/*.wasm
            ./**/output/*.abi.json
          if-no-files-found: error

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        with:
          path: assets

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create vNext --draft --title="Release draft from Github Actions" --generate-notes
          for i in $(find ./assets -type f); do
            gh release upload vNext ${i}#checksum $(sha256sum ${i})
          done
